version: "3"

services:
   backend:
      build: ./php
   frontend:
      build: ./html
      depends_on:
         - backend
      volumes:
         - ./production.conf:/etc/nginx/conf.d/default.conf
         - ./html:/usr/share/nginx/html
         - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
         - /docker-volumes/etc/letsencrypt/live/brandonhuffman.dev/fullchain.pem:/etc/letsencrypt/live/brandonhuffman.dev/fullchain.pem
         - /docker-volumes/etc/letsencrypt/live/brandonhuffman.dev/privkey.pem:/etc/letsencrypt/live/brandonhuffman.dev/privkey.pem

      ports:
         - 80:80
         - 443:443